### ISSUE TITLE
Ginga widget: Datasrc caching is not used?

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#108]
@ejeschke , please correct me if I am wrong, but I think currently only the reference viewer has access to the built-in caching mechanism (`Datasrc`) via `Channel`? Does that mean, `Datasrc` usage needs to be added separately for caching to be possible in `astrowidgets`? Please advise. Thanks!

**Comment by ejeschke** [comment]
That is correct. The widget only handles displaying what has been plotted on it (which, when you use `set_image()` plots and replots using a single image object).  You'd have to add that caching separately.

If you were going to do so, you could use ginga's `Datasrc`, but I'd recommend using something standard like `collections.deque` if you just need an N-item store.

**Comment by pllim** [comment]
@ejeschke , I would prefer a consistent approach between reference viewer and the widget, if possible. Can you please elaborate on your recommendation of `deque` over `Datasrc`?

**Comment by ejeschke** [comment]
Feel free to use `Datasrc` (there is nothing wrong with it). I was just recommending `deque` because it would be better to use a standard library function if it has all the features you need (e.g. simple fixed item cache).  That wasn't around when Ginga was first built, so I made `Datasrc`.

**Comment by pllim** [comment]
@ejeschke , in that case, do you have plans to deprecate `Datasrc` and use `deque` for Ginga itself?

**Comment by ejeschke** [comment]
Probably not, as there is now an API to support.  But I might consider refactoring `Datasrc` in the future. Looking at `deque`, it looks like it doesn't offer random access key-based access, which the reference viewer requires, so I probably wouldn't go with that. But it would be sufficient if you were building a simple viewer that needed to just go forward or backward through the images you loaded.

If refactoring `Datasrc`, I'd probably subclass some of the ABC's in `collections`.

**Comment by pllim** [comment]
@mwcraig and @eteq , how important is caching for you as far as the widgets are concerned? Should I waste time trying to implement this for the Ginga backend in `core.py`? Please advise. Thanks!

**Comment by ejeschke** [comment]
Couldn't you use the same caching mechanism for all the backends?

**Comment by pllim** [comment]
> Couldn't you use the same caching mechanism for all the backends?

:woman_shrugging:  I haven't seen any other backend implementations yet.

**Comment by pllim** [comment]
I have asked this another way in #112.
