### ISSUE TITLE
Make @pllim and @mwcraig maintainers so we can set up CI/ReadTheDocs/etc...

### ISSUE THREAD

**Issue by mwcraig** [astropy/astrowidgets#11]
ping @eteq

**Comment by eteq** [comment]
Hmm... I'm not sure I can? That is, I'm not sure it's possible to give admin rights on a personal rather than organization repo.

**Comment by mwcraig** [comment]
Right, forgot about that. Should we move the repo?

**Comment by pllim** [comment]
I have set up http://readthedocs.org/projects/astrowidgets/ but I cannot activate the webhook without repo admin access. Please private message me with your RTD usernames, so I can add you as RTD admins there.

**Comment by eteq** [comment]
Actually, it's probably best for you to be able to fiddle with it yourself - if there are no objections from either of you (@pllim or @mwcraig), I can just move this to the astropy org, although I'll want to add a big "warning, this is deeply in progress, nothing to see here, move along" sort of warning in the README.

**Comment by mwcraig** [comment]
Sounds good to me!

**Comment by pllim** [comment]
`baldrick` was moved to `openastronomy`. What is the difference between the two orgs?

**Comment by eteq** [comment]
@pllim - it's a bit nebulous, bit `openastronomy` is an umbrella that includes groups like `sunpy`, `yt`, `juliaastro`, etc.  baldrick isn't really python-specific so I guess that makes sense, but this is a python project so it seems more appropriate in `astropy`.

(I think I have admin rights over both/am on the steering committees, but I also feel more comfortable making command decisions in astropy :wink:)

**Comment by eteq** [comment]
Alright done!
