### ISSUE TITLE
Feature Request: overlay regions or images

### ISSUE THREAD

**Issue by eriniocentric** [astropy/astrowidgets#115]
Hi, I am using the get_markers feature often to mark boxes and regions. Is there any way to over plot a box made by two markers (not just the vertices)? Similarly, I'd like to plot a contour map overtop an image. Is there a way to over plot a contour?  

I use load_array(contour) and it will just replace the existing image that is displayed.

Thanks!

**Comment by pllim** [comment]
1. Box -- Theoretically, your box is a marker that is box-shaped. So, to enable this, the widget's `_marker` method needs to support `ginga.canvas.types.basic.Box` object.

https://github.com/astropy/astrowidgets/blob/cfc8feee655aef250ed510185efada0201f47204/astrowidgets/core.py#L474

https://github.com/ejeschke/ginga/blob/master/ginga/canvas/types/basic.py#L453 (the available parameters you can set are defined here)

2. Contour -- I think this is still an unimplemented feature in `Ginga` (ejeschke/ginga#396). Theoretically, once contour is calculated, one can construct a "free form" shape and overlay it on top of displayed image. Over at Ginga's standalone viewer (non-widget interface), the contour is displayed within the [Pick plugin](https://ginga.readthedocs.io/en/latest/manual/plugins_local/pick.html) using Matplotlib.

I wonder if you can use [imexam](https://imexam.readthedocs.io/) to accomplish the above in conjunction with the widget.

**Comment by eriniocentric** [comment]
Thanks for the tips and replies!! I'll try to see if I can get a canvas working. I tried once before but failed. 

I'm really big into the ipywidgets these days as I'm reliant on jupyter notebooks quite a bit so not sure I want to make the shift to imexam but i'll look into it. astrowidgets made it easy to integrate

**Comment by pllim** [comment]
Well... I wonder if you can use `imexam` to extract the contour info and then overlay that info as Polygon canvas object in the widget? 🤔 

Ref: https://imexam.readthedocs.io/en/0.9.1/imexam/examples.html#use-the-imexamine-library-standalone-to-create-plots-without-viewing
