### ISSUE TITLE
rename offset_to to offset_byand have it use units

### ISSUE THREAD

**Issue by eteq** [astropy/astrowidgets#139]
This idea was triggered by looking at the implementation of another astrowidgets-conforming API in spacetelescope/jdaviz#705 :

1. I think the `offset_to` method  is better named `offset_by`.  This [aligns better with astropy.coordinates](https://docs.astropy.org/en/latest/api/astropy.coordinates.offset_by.html) and I think it makes it just a bit clearer that you are giving the *delta* coordinates instead of actual coordinates
2. I think we can dispense with the `skycoord_offset` keyword by instead using the units of `dx`/`dy` - if they are either `pixel` or dimensionless that can be interpreted as pixel offsets, and any other unit can assume `SkyCoord`/other WCS ("other wcs" can be implemented in the future, but I'm  just trying not to accidentally specify ourselves out of it)

My proposal would be to keep in `offset_to` with its current API but have it start raising a deprecation warning (and internally it would call the new `offset_by`)

And yes, `offset_to` was my original suggestion.  But I think it was wrong after seeing it in action!

**Comment by eteq** [comment]
Oh, and @pllim saw this idea already in spacetelescope/jdaviz#705, but @mwcraig do you have any thoughts pro- or anti- this?

**Comment by mwcraig** [comment]
I'm fine with this -- can it wait until we make some progress on the refactoring that @pllim started or does this need an implementation ASAP?

**Comment by pllim** [comment]
I don't foresee being able to refactor anything over here in the near future. Also see https://github.com/astropy/astrowidgets/pull/131#issuecomment-871548303

**Comment by pllim** [comment]
I see two different things proposed here. I think it is more practical to keep `offset_to` and `offset_by` separate; i.e:

* `offset_to`: Deprecate. Keep old API.
* `offset_by`: New API only.
