### ISSUE TITLE
Zoom: Why two ways to do the same thing?

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#144]
There can be only one.

https://github.com/astropy/astrowidgets/blob/c594308246b5dde60db7900a532cf4cc53855756/astrowidgets/core.py#L409-L427

**Comment by mwcraig** [comment]
I think these are two different operations, though arguably the names could be better.

`zoom_level`: a specific zoom relative to the scale (1 screen pixel) = (1 image pixel)

`zoom`: a factor by which to change the current `zoom_level`, e.g. "I want to zoom in another factor 1.5" . A better name might be `zoom_by`.

**Comment by pllim** [comment]
But do we need both? 🤔

**Comment by mwcraig** [comment]
I think we do in the context of user interactions. Imagine you have been doing some zoom in/zoom out by mouse or scroll wheel or whatever. You probably have no idea what your current `zoom_level` is but might know that you want to `zoom` by additional factor in or out. 

One could calculate the new `zoom_level` manually but that seems cumbersome. 

The other difference I see between them is that `zoom_level` is part of the state of the view/a property and `zoom` is an action/method.

**Comment by pllim** [comment]
So, should we remove the `zoom_level` setter and make it read-only?

**Comment by mwcraig** [comment]
I'm inclined not to because I see setting a specific level and zooming by a particular factor as different things. In a widget implementation, allowing `zoom_level` to be settable in the API means it is fine to make it a traitlet, which makes it easy to link the zoom level of two browsers.

**Comment by pllim** [comment]
Ah, gotcha...
