### ISSUE TITLE
TST: image.stretch setter fails with Ginga dev

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#159]
@ejeschke , something changed upstream,  maybe from ejeschke/ginga#1045 ? Can Ginga dev be made backward compatible? Hope you can advise. Thanks!

https://github.com/astropy/astrowidgets/blob/3382c7e2a80eabb76fd802779af4ea85d5ef6837/astrowidgets/core.py#L817

```
_________________________________ test_stretch _________________________________

    def test_stretch():
        image = ImageWidget()
        with pytest.raises(ValueError) as e:
            image.stretch = 'not a valid value'
        assert 'must be one of' in str(e.value)
    
        image.stretch = 'log'
>       assert isinstance(image.stretch, (ColorDistBase))
E       assert False
E        +  where False = isinstance(None, ColorDistBase)
E        +    where None = ImageWidget(...).stretch

astrowidgets/tests/test_api.py:196: AssertionError
```

**Comment by ejeschke** [comment]
@pllim, will surely fix. The refactoring should be purely internal, for the most part. But perhaps I missed a small detail. Will take a look.

**Comment by ejeschke** [comment]
@pllim, see #160
