### ISSUE TITLE
ENH: Move ipyfits over

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#3]
As discussed during Scipy 2018.

**Comment by mwcraig** [comment]
Closing, since I think we've done this

**Comment by pllim** [comment]
@mwcraig , do you mean indirectly via Ginga API or something? I don't remember seeing any PR on moving ipyfits itself over here. Hope you could clarify. Thanks!

**Comment by mwcraig** [comment]
I'll take a look in ipyfits, but I think most of the functionality that had been implemented there is now here. What isn't over here yet is non-ginga backend for the image display. I hope to work on that this week....
