### ISSUE TITLE
Ginga widget: Make opencv truly optional

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#31]
It works without ``opencv``, just slower when rendering image rotation and such.

- [ ] Make it truly optional in widget constructor.
- [ ] Remove it from CI dependencies and setup. (Removed from setup in #33)
- [ ] Make it optional in installation doc.

**Comment by pllim** [comment]
p.s. I am not sure what is ``opencv-python`` as ``conda`` cannot find it on Linux. It is just ``opencv`` for me. :woman_shrugging:

**Comment by ejeschke** [comment]
In miniconda it is just `opencv`.
