### ISSUE TITLE
Make pixel offsets more explicit

### ISSUE THREAD

**Issue by mwcraig** [astropy/astrowidgets#47]
RIght now in some places you can specify whether you want pixel numbering to start at 0 or 1 (e.g. in [`add_markers`](https://github.com/astropy/astrowidgets/blob/master/astrowidgets/core.py#L496)) but in other places an offset of 1 is baked in, for example in [the method that calculates the pixel location](https://github.com/astropy/astrowidgets/blob/master/astrowidgets/core.py#L164) to display.

I'm thinking that setting that preference once when the object is created might be a better way to go. 

Also in [the other mouse callback](https://github.com/astropy/astrowidgets/blob/master/astrowidgets/core.py#L164).

**Comment by pllim** [comment]
Do people actually view coordinates in a 0-indexed way? I guess I am too used to DS9 display. :grimacing:

**Comment by mwcraig** [comment]
🤣 my bias is opposite, because I started doing observational astronomy with python and skipped ds9/IRAF/pyraf altogether.

There is an interoperability issue if the 1-indexed approach is baked in: a table of positions of sources returned by photutils is 0-indexed, so add markers for them works only if the pixel offset is zero.

I'm guessing we don't want to force one or the other but do want to make it easy to state one's preference once and make sure it is used throughout.

**Comment by pllim** [comment]
Yes, I agree that it should be configurable and consistently so.
