### ISSUE TITLE
Add markers via positions that are `SkyCoord`s makes the viewer really laggy

### ISSUE THREAD

**Issue by mwcraig** [astropy/astrowidgets#50]
I haven't had a chance to glance at the source code yet, but I'm guessing that in this case they maybe aren't added as a single compound object.

**Comment by pllim** [comment]
They are:

https://github.com/astropy/astrowidgets/blob/b8837870e17c39c7f4b3c54243b343c661a2433a/astrowidgets/core.py#L567-L569

But the main difference is that for the `SkyCoord` case, they are added as `'wcs'` data type, so there is extra overhead in converting RA/DEC to data coordinates. Open to ideas on how you want to optimize it.
