### ISSUE TITLE
ImageWidget buffer does not render nicely in static notebook view

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#67]
I have a notebook PR (spacetelescope/dat_pyinthesky#7) where I do not clear the output on purpose so people can see how things are supposed to appear without running the notebook. I noticed this when I view the notebook on GitHub:

![widget_noshow](https://user-images.githubusercontent.com/2090236/53436126-73c45580-39c8-11e9-9942-5b5bf8270bdf.jpg)

Meanwhile, a separate notebook that does a similar thing but using non-interactive Matplotlib display renders the image fine.

If there is nothing we can do about this, you can slap a "won't fix" label and close this.

**Comment by pllim** [comment]
p.s. Maybe this is more of a `ipywidgets` issue, as I see that the button widgets also do not render in a WYSIWYG way.

**Comment by michiboo** [comment]
Hi! I am Micky, looking for apply for GSOC for this project!
I was looking into this problem and found a useful information about this issue on ipywidgets documentation

"""A text representation of the widget is printed if the widget control is not available. It may mean the widget JavaScript is still loading. If the message persists in the Jupyter Notebook or JupyterLab, it likely means that the widgets JavaScript library is either not installed or not enabled. See the installation instructions above for setup instructions.

If you see this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn’t currently support widgets."""

So there is nothing we can do on static notebook.

**Comment by pllim** [comment]
Yes, that was what I suspected (and afraid of). Thanks!

**Comment by pllim** [comment]
cc @eteq , how sure how much this would be a blocker for rendering notebooks over at `notebooks`.

**Comment by pllim** [comment]
Re: applying to GSoC -- Please see https://github.com/astropy/astropy/wiki/GSoC-Guidelines , @michiboo

**Comment by eteq** [comment]
Wait, I'm not sure you can interpret it quite that way, @pllim and @michiboo : when it says "for example, a static rendering on GitHub or NBViewer", that doesn't mean *all* static views don't support it... In principle as long as you can embed the javascript for the widget in the static view it could still work.

That said, a better approach *might* be to build machinery that turns an `ImageWidget` into a regular `Image` upon saving or converting to the static view... I'm not sure how to do this exactly, but it should be possible.

**Comment by pllim** [comment]
Should I re-open this issue then? Or should this be upstream somewhere in `ipywidgets`?

**Comment by michiboo** [comment]
@pllim  Thanks for the information!

@eteq Would it be better if we export the notebook to html using nbconvert? It will preserve the widget.
