### ISSUE TITLE
Adding new shape for markdown 

### ISSUE THREAD

**Issue by michiboo** [astropy/astrowidgets#68]
From Ginga there is additional shape that can be added to markdown, I am wondering which shapes is appropriate? 
the following could be added:
rectangle, line, Point, Polygon, FreePolygon, RightTriangle, Triangle, Ellipse, Square, BezierCurve, Box, squarebox

**Comment by pllim** [comment]
Hi. Can you please provide more context? There is no "one right shape to rule them all", it really depends on what you are using it for...

**Comment by michiboo** [comment]
I was reading the DevNotes and notice this sentence at the end.
 "I also think we need at least minimal ability to change/set marker color, shape very early on."

Thought I can contribute a little by adding option to change different shape for marker, as there is only circle available at the moment.

also i wonder if it is a good idea to add function to connect all the marker/ specific marker name by line?

**Comment by pllim** [comment]
Ah, you are looking at this?

https://github.com/astropy/astrowidgets/blob/3e206c917e9e60ed4458b454468703bacfe84ba7/astrowidgets/core.py#L424-L431

`Point` is probably the next low-hanging fruit if you want to take a stab at it. `Param` values for `Point` is here in Ginga: https://github.com/ejeschke/ginga/blob/6682ed7b8ec7602c2dc71a71893a7c5703e02cfa/ginga/canvas/types/basic.py#L1050

Connecting by line is probably an overkill, as `Polygon` shape automatically does that.

**Comment by michiboo** [comment]
Thanks! I could also implement polygon shape for set of points if that's this function is desire.

**Comment by pllim** [comment]
Let's save `Polygon` for later, as it is slightly more complicated to use.

**Comment by michiboo** [comment]
Hi! for test_reset_markers() in test_api.py, There is also a need  of doing the following:
" # TODO add test of actually removing markers...`"
Can I do it?
also which way is best for me contact people here?

**Comment by pllim** [comment]
> Can I do it?

This is open source code. Nothing is stopping you. 😄 

> which way is best for me contact people here?

`joinslack.astropy.org`
