### ISSUE TITLE
Preliminary work on method for identifying the nearest point source to a click on an image 

### ISSUE THREAD

**Issue by michiboo** [astropy/astrowidgets#76]
@mwcraig  @pllim  @astrofrog 
As I reading up the ideas for Astrowidgets I noticed this idea
"Develop a method for identifying the nearest point source to a click on an image 
(very preliminary work on this is available)"

I want to ask where I could find the preliminary work of this?
Thank you!

**Comment by mwcraig** [comment]
Look in this notebook in the cell that has a ton of code. Many things are going on in there, but put of it is repeatedly finding the "center of mass" of the light, adjusting until it converges on a center or too many attempts have been made. Don't be shy about asking questions...that code is not documented or entirely coherent.

https://github.com/mwcraig/obs-astronomy-binder/blob/master/ORIGINALS-OF-USEFUL-NOTEBOOKS/viewer-seeing-profile.ipynb

**Comment by pllim** [comment]
@ejeschke also implemented something similar in https://github.com/ejeschke/ginga/blob/21b8e52cbb2272e742a98f75ebf8de26206063b1/ginga/util/iqcalc.py#L239 . In the Ginga's `Pick` plugin, when you click on a point source, it calculates its center (the nearest peak) and move the box there.

I am sure `photutils` also has some function to do this but maybe requiring `photutils` at this stage is overkill?
