### ISSUE TITLE
Notebook jumps to show entire viewer on mouseover

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#89]
As asked on Slack, "I notice that the notebook jumps up to show the entire viewer when I am a few cells down and I happen to mouse over the viewer. Is this a bug or feature? (Chrome on Windows 10)"

@mwcraig , "That is a bug I thought I had fixed....I noticed (and was irritated by it) a couple weeks ago too. I’ll look at this install of the install issue... It is a side effect of setting the focus to the image, which I needed to do to make keyboard events work in lab"

Thanks, Matt!

**Comment by mwcraig** [comment]
I'm moving this to [ipyevents](https://github.com/mwcraig/ipyevents), because it is causing the problem (which occurs in both classic and lab)

**Comment by mwcraig** [comment]
Actually, not transferring, because can't do that across orgs.

**Comment by mwcraig** [comment]
Should be fixed in ipyevents 0.6.3, released moments ago on pip.

Please give it a try and close this if it is fixed for you (I tested in lab but not classic)!

**Comment by pllim** [comment]
Yes, it works in classic now. Thank you! 🙏
